In [5]:
import pandas as pd

In [13]:
# The code was removed by Watson Studio for sharing.

fever  bodyPain  age  runnyNose  diffBreath  infectionProb
0   97.784580         0   51          0           1              0
1  100.187984         1   79          0           1              0
2  100.838977         0   81          1           1              0
3   97.455994         0   17          0          -1              0
4   98.473230         0   48          0           1              1

In [14]:
df

fever  bodyPain  age  runnyNose  diffBreath  infectionProb
0      97.784580         0   51          0           1              0
1     100.187984         1   79          0           1              0
2     100.838977         0   81          1           1              0
3      97.455994         0   17          0          -1              0
4      98.473230         0   48          0           1              1
5     100.311724         1   36          1           0              0
6      98.625183         1   35          0           0              1
7      97.697418         0   99          0           1              0
8     100.734535         1   47          0           0              0
9     100.735405         0   64          0          -1              1
10     97.328843         0   16          1           1              1
11     97.484206         1   94          1           0              1
12     99.700346         1   28          1          -1              1
13     97.862108         1   57          1          -1              1
14    100.703156         1    9          1          -1              0
15     99.943704         1   54          0          -1              0
16     99.846167         1   39          0           0              1
17     98.071585         1   84          1           1              0
18    100.787850         0    3          0           0              0
19     99.318770         0   95          0           1              1
20     98.814713         1   26          0           0              1
21     97.634608         0    7          1          -1              0
22     99.470235         1   46          0           1              0
23     99.657235         0   38          0           0              0
24    100.645917         0    0          0           1              1
25     99.507992         1   15          1          -1              0
26    100.789260         1   62          0           0              1
27    100.985346         1   21          1          -1              0
28     98.156717         1   75          1           0              1
29     98.140420         1    8          1          -1              1
...          ...       ...  ...        ...         ...            ...
2245   99.061297         1   46          1          -1              1
2246   98.719925         0   36          1           1              0
2247   98.102327         0   32          1           0              0
2248   99.042230         0  100          1           1              0
2249   97.124860         1   41          1           0              1
2250   97.505658         0   53          0           1              0
2251   98.060764         0   46          0           0              1
2252  100.587615         0   71          0           1              0
2253   99.312626         0   29          0           0              1
2254   99.051154         1   98          1           0              1
2255   98.337541         0   84          1           1              1
2256   98.674697         0    4          0           1              1
2257  100.538396         0   97          0           1              1
2258  100.340706         0   16          0           0              0
2259   99.035123         1   13          0           1              1
2260   97.215474         0   19          1           1              1
2261   99.474916         0   29          0           1              1
2262  100.002892         0   86          0           1              1
2263  100.925130         0   99          0           0              0
2264   98.143359         0    9          0           1              0
2265  100.037094         0    4          1           1              1
2266  100.954832         1   74          1          -1              0
2267   97.646866         0   54          0           1              1
2268   98.670778         0   84          1          -1              0
2269   97.877651         0   45          1          -1              0
2270   98.344591     

In [6]:
df.tail(10)

fever  bodyPain  age  runnyNose  diffBreath  infectionProb
2265  100.037094         0    4          1           1              1
2266  100.954832         1   74          1          -1              0
2267   97.646866         0   54          0           1              1
2268   98.670778         0   84          1          -1              0
2269   97.877651         0   45          1          -1              0
2270   98.344591         1   18          0          -1              1
2271   97.945532         0   52          1           0              0
2272   97.836398         0   84          0           1              0
2273   99.298029         0   43          1          -1              0
2274  100.078420         0   82          0           0              1

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2275 entries, 0 to 2274
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   fever          2275 non-null   float64
 1   bodyPain       2275 non-null   int64  
 2   age            2275 non-null   int64  
 3   runnyNose      2275 non-null   int64  
 4   diffBreath     2275 non-null   int64  
 5   infectionProb  2275 non-null   int64  
dtypes: float64(1), int64(5)
memory usage: 106.8 KB


In [8]:
df['diffBreath'].value_counts()

 1    764
-1    760
 0    751
Name: diffBreath, dtype: int64

In [9]:
df.describe()

fever     bodyPain          age    runnyNose   diffBreath  \
count  2275.000000  2275.000000  2275.000000  2275.000000  2275.000000   
mean     99.005647     0.516484    48.438681     0.504615     0.001758   
std       1.158416     0.499838    29.323689     0.500089     0.818646   
min      97.005016     0.000000     0.000000     0.000000    -1.000000   
25%      98.007091     0.000000    23.000000     0.000000    -1.000000   
50%      98.983539     1.000000    48.000000     1.000000     0.000000   
75%     100.021038     1.000000    75.000000     1.000000     1.000000   
max     100.995193     1.000000   100.000000     1.000000     1.000000   

       infectionProb  
count    2275.000000  
mean        0.483956  
std         0.499852  
min         0.000000  
25%         0.000000  
50%         0.000000  
75%         1.000000  
max         1.000000

In [15]:
import numpy as np

In [16]:
def data_split(data, ratio):
    np.random.seed(42)
    shuffled = np.random.permutation(len(data))
    test_set_size = int(len(data) * ratio)
    test_indices = shuffled[:test_set_size]
    train_indices = shuffled[test_set_size:]
    return data.iloc[train_indices], data.iloc[test_indices]

In [17]:
np.random.permutation(7)

array([2, 3, 0, 4, 1, 5, 6])

In [18]:
train, test = data_split(df, 0.2)

In [19]:
train

fever  bodyPain  age  runnyNose  diffBreath  infectionProb
1523   98.478332         1   15          0           1              1
1786   98.721089         0   47          1           0              1
1962   98.543219         1   11          1          -1              0
8     100.734535         1   47          0           0              0
1691   99.048457         0   94          0           0              1
2110   98.446965         1   54          0           1              0
450    99.426525         0   58          1           0              0
316    99.141938         1   34          1          -1              0
1859   97.463938         1   60          0           0              0
812   100.598908         0    9          1           1              1
1909   98.558545         1    4          1           1              1
427    98.225170         1    9          0          -1              0
374    97.143476         1    1          1           0              0
105    99.815690         0   68          0          -1              1
1601   98.366165         1   67          0           0              0
121    98.867442         0    4          0           1              1
173    99.498666         0   86          0          -1              0
1511   99.021009         1   57          1          -1              0
765   100.088283         0   44          1          -1              0
1709   98.787072         0   11          1          -1              1
1898  100.065248         1   61          0           1              0
1444   99.542996         1   45          0           1              1
915    99.559527         1    2          1          -1              1
1845   99.974983         1   94          1           1              1
115    98.182894         0   24          1          -1              0
76     98.001094         0   52          0          -1              1
416    99.121863         1    4          0           0              1
613    99.987739         1   70          1          -1              0
2008   97.964379         1   40          1           1              1
610    98.386302         0   77          1           0              0
...          ...       ...  ...        ...         ...            ...
1267  100.377533         1   81          0           1              1
1899  100.037278         1   98          0           1              0
562    97.856045         1   77          1           0              0
189    98.060713         1   67          1           1              0
1806   98.064059         1   58          0          -1              1
975   100.143832         0   73          1          -1              1
2047   99.259332         1   49          0           0              0
1082   99.590183         0    1          0          -1              0
474    99.719818         0   96          1           0              0
747    98.027561         0   27          1           1              1
21     97.634608         0    7          1          -1              0
459    99.115396         0   57          1          -1              1
1184   97.910424         0   83          0           0              1
955    98.657336         0   57          0           1              0
1215   97.485756         0   95          0           1              0
1515   98.470679         1   64          1          -1              1
769    99.542899         1   98          0           1              0
1685  100.400277         0   99          0           0              0
130    98.699606         0   62          0           0              0
2135   98.579773         1   71          0           1              1
1482   97.668651         1   89          1          -1              1
330    99.615434         1   71          0          -1              0
1238   97.629602         0   68          0           0              1
466   100.549359         0    0          0           0              0
2169   99.074682         1   81          0          -1              0
1638   97.218282     

In [20]:
test

fever  bodyPain  age  runnyNose  diffBreath  infectionProb
2064   99.670483         0   26          0           1              1
1321   97.806860         0   16          0           1              1
859    98.414240         1   60          0           0              1
408    98.921074         0    0          0           1              1
629    99.241710         1   27          1           0              1
1344   99.733845         0   24          1           0              1
527    97.598287         1   15          0           0              1
29     98.140420         1    8          1          -1              1
254   100.408016         1   87          0          -1              1
1207   98.221463         0   46          0          -1              0
1422   98.581058         1   26          0           0              0
1427   98.843939         0   67          1           0              1
1592   98.607502         1   68          1           0              1
1889   99.001267         0   22          0           0              0
303   100.889343         1   94          0           1              1
1245   98.736303         0   27          1           1              1
1259   99.560015         0   14          0           0              1
2107   97.419253         1   64          1           1              1
2012   98.494247         0   68          0           1              0
1360  100.928854         1   41          0           1              0
1864   97.517970         0   39          1           0              0
2132   97.431762         1   80          1           1              1
2121   98.774164         1   23          1          -1              1
1775   99.029252         1   90          1          -1              0
1143   98.433486         0   42          1           0              0
482   100.952660         0   15          1           1              1
1689   98.001680         0   13          0           1              1
134    97.607909         0    4          1           1              0
1287   99.932896         0    5          1           1              1
1593   99.094241         1   42          1           0              0
...          ...       ...  ...        ...         ...            ...
13     97.862108         1   57          1          -1              1
361    99.289832         1    9          0           1              1
1452  100.742597         0   10          1          -1              0
296    98.020087         0   56          0           1              1
1146  100.031148         1   30          0          -1              1
1882   98.362228         0   21          1           0              1
440    97.881951         0   21          0          -1              0
409   100.731990         1   24          1          -1              0
564    97.246024         0   99          0           0              0
1912   98.505300         0   96          1          -1              1
611    98.869500         0   52          0           1              0
387    97.225336         1   54          1           1              0
2011   97.427034         1   65          1           1              1
1626   98.898135         0   35          1          -1              1
1341   99.513115         1   10          1           0              0
382    99.860786         0   57          1          -1              0
1564   98.450334         0   82          0           1              1
1315   99.372046         1   22          0           0              1
445    97.926501         1    8          1           1              1
944    99.625551         1   65          1           0              1
988   100.027922         0    4          1          -1              0
1604   98.505520         1   85          0           1              0
177   100.264206         1   17          0          -1              0
677    99.296478         0   16          0          -1              1
2246   98.719925         0   36          1           1              0
203    97.862912     

In [21]:
X_train = train[['fever', 'bodyPain', 'age', 'runnyNose', 'diffBreath']].to_numpy()
X_test = test[['fever', 'bodyPain', 'age', 'runnyNose', 'diffBreath']].to_numpy()

In [22]:
Y_train = train[['infectionProb']].to_numpy().reshape(1820 ,) 
Y_test = test[['infectionProb']].to_numpy().reshape(455 ,)

In [23]:
X_train

array([[ 98.47833206,   1.        ,  15.        ,   0.        ,
          1.        ],
       [ 98.72108922,   0.        ,  47.        ,   1.        ,
          0.        ],
       [ 98.54321892,   1.        ,  11.        ,   1.        ,
         -1.        ],
       ...,
       [ 97.56056446,   1.        ,   6.        ,   1.        ,
          0.        ],
       [ 99.44315155,   0.        ,   7.        ,   0.        ,
          0.        ],
       [100.123163  ,   0.        ,  90.        ,   0.        ,
          0.        ]])

In [24]:
Y_train

array([1, 1, 0, ..., 0, 0, 1])

In [25]:
Y_train

array([1, 1, 0, ..., 0, 0, 1])

In [26]:
from sklearn.linear_model import LogisticRegression

In [27]:
clf = LogisticRegression()
clf.fit(X_train, Y_train)

/opt/ibm/conda/miniconda3.6/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [28]:
inputFeatures = [102, 1, 22, -1, 1]
infProb = clf.predict_proba([inputFeatures])[0][1]

In [29]:
infProb

0.4938743128765193